# Generated by Django 5.2.11 on 2026-03-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_branch_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('store', 'name')},
        ),
    ]
