# Generated by Django 5.2.11 on 2026-03-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunt', '0006_workerkpi'),
        ('store', '0007_storesettings_auto_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('trial', 'Sinov (30 kun)'), ('basic', 'Asosiy'), ('pro', 'Professional'), ('enterprise', 'Korporativ')], max_length=20, unique=True, verbose_name='Reja turi')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik narx (UZS)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Yillik narx (UZS)')),
                ('yearly_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yillik chegirma (%)')),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='Maks. filiallar')),
                ('max_warehouses', models.PositiveIntegerField(default=1, verbose_name='Maks. omborlar')),
                ('max_workers', models.PositiveIntegerField(default=3, verbose_name='Maks. xodimlar')),
                ('max_products', models.PositiveIntegerField(default=100, verbose_name='Maks. mahsulotlar')),
                ('has_subcategory', models.BooleanField(default=False, verbose_name='Subkategoriyalar')),
                ('has_sale_return', models.BooleanField(default=False, verbose_name='Qaytarishlar')),
                ('has_wastage', models.BooleanField(default=False, verbose_name='Isrof yozuvlari')),
                ('has_stock_audit', models.BooleanField(default=False, verbose_name='Inventarizatsiya')),
                ('has_kpi', models.BooleanField(default=False, verbose_name='KPI moduli')),
                ('has_price_list', models.BooleanField(default=False, verbose_name="Narx ro'yxati")),
                ('has_multi_currency', models.BooleanField(default=False, verbose_name="Ko'p valyuta")),
                ('has_supplier', models.BooleanField(default=False, verbose_name='Yetkazib beruvchi')),
                ('has_export', models.BooleanField(default=False, verbose_name='Export (Excel/PDF)')),
                ('has_dashboard', models.BooleanField(default=False, verbose_name='Dashboard')),
                ('has_qr_bulk', models.BooleanField(default=False, verbose_name='Bulk QR kod')),
                ('has_audit_log', models.BooleanField(default=False, verbose_name='Audit log')),
                ('has_telegram', models.BooleanField(default=False, verbose_name='Telegram bot (v2)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif reja',
                'verbose_name_plural': 'Tarif rejalar',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Sinov davri'), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='trial', max_length=15, verbose_name='Holati')),
                ('is_yearly', models.BooleanField(default=False, verbose_name="Yillik to'lov")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name="Oxirgi to'lov sanasi")),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Oxirgi to'lov summasi (UZS)")),
                ('notified_10d', models.BooleanField(default=False, verbose_name='10 kun ogohlantirish')),
                ('notified_3d', models.BooleanField(default=False, verbose_name='3 kun ogohlantirish')),
                ('notified_1d', models.BooleanField(default=False, verbose_name='1 kun ogohlantirish')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='store.store', verbose_name="Do'kon")),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.subscriptionplan', verbose_name='Tarif reja')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDowngradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=20, verbose_name="Ob'ekt turi")),
                ('object_id', models.PositiveIntegerField(verbose_name="Ob'ekt ID")),
                ('previous_status', models.CharField(max_length=10, verbose_name='Oldingi holati')),
                ('deactivated_at', models.DateTimeField(auto_now_add=True, verbose_name='Inactive qilingan vaqt')),
                ('reactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Qayta faollashtirilgan vaqt')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downgrade_logs', to='subscription.subscription', verbose_name='Obuna')),
            ],
            options={
                'verbose_name': 'Downgrade log',
                'verbose_name_plural': 'Downgrade loglar',
                'ordering': ['deactivated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi (UZS)")),
                ('is_yearly', models.BooleanField(default=False, verbose_name="Yillik to'lov")),
                ('period_from', models.DateField(verbose_name='Davr boshi')),
                ('period_to', models.DateField(verbose_name='Davr oxiri')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accaunt.worker', verbose_name="Qo'shgan admin")),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscription.subscription', verbose_name='Obuna')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscriptionplan', verbose_name="Tarif reja (to'lov vaqtida)")),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-paid_at'],
            },
        ),
    ]
