# Generated by Django 5.2.11 on 2026-02-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunt', '0003_alter_worker_branch_verbose_name'),
        ('store', '0002_alter_branch_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.store', verbose_name="Do'koni")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kilogram'), ('g', 'Gram'), ('litr', 'Litr'), ('metr', 'Metr'), ('m2', 'Kvadrat metr'), ('yashik', 'Yashik'), ('qop', 'Qop')], default='dona', max_length=10, verbose_name="O'lchov birligi")),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Xarid narxi (UZS)')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sotish narxi (UZS)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shtrix-kod')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warehouse.category', verbose_name='Kategoriyasi')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store', verbose_name="Do'koni")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=10, verbose_name='Harakat turi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Miqdori')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store.branch', verbose_name='Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.product', verbose_name='Mahsulot')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='accaunt.worker', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Qoldiq miqdori')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.branch', verbose_name='Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Ombor qoldig'i",
                'verbose_name_plural': 'Ombor qoldiqlari',
                'ordering': ['product__name'],
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
