# Generated by Django 5.2.11 on 2026-03-02 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accaunt', '0004_remove_worker_extra_permissions_worker_permissions_and_more'),
        ('store', '0003_alter_branch_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.store', verbose_name="Do'koni")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kilogram'), ('g', 'Gram'), ('litr', 'Litr'), ('metr', 'Metr'), ('m2', 'Kvadrat metr'), ('yashik', 'Yashik'), ('qop', 'Qop')], default='dona', max_length=10, verbose_name="O'lchov birligi")),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Xarid narxi (UZS)')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sotish narxi (UZS)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shtrix-kod')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warehouse.category', verbose_name='Kategoriyasi')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store', verbose_name="Do'koni")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
                'unique_together': {('store', 'barcode'), ('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzili')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='store.store', verbose_name="Do'koni")),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('transfer', "Ko'chirish")], max_length=10, verbose_name='Harakat turi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Miqdori')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='store.branch', verbose_name='Filialdan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.product', verbose_name='Mahsulot')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='store.branch', verbose_name='Filialga')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='accaunt.worker', verbose_name='Hodim')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='warehouse.warehouse', verbose_name='Ombordan')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='warehouse.warehouse', verbose_name='Omborga')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Qoldiq miqdori')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.branch', verbose_name='Filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.product', verbose_name='Mahsulot')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Qoldiq',
                'verbose_name_plural': 'Qoldiqlar',
                'ordering': ['product__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', False), ('warehouse__isnull', True)), models.Q(('branch__isnull', True), ('warehouse__isnull', False)), _connector='OR'), name='stock_exactly_one_location')],
                'unique_together': {('product', 'branch'), ('product', 'warehouse')},
            },
        ),
    ]
