# Generated by Django 5.2.11 on 2026-02-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_branch_unique_together'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'barcode'), ('store', 'name')},
        ),
    ]
