# Generated by Django 5.2.11 on 2026-03-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0006_workerkpi'),
        ('store', '0006_storesettings_eur_cny'),
        ('warehouse', '0013_wastage_stockaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Kompaniya')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('debt_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Qarz balansi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='store.store', verbose_name="Do'koni")),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi',
                'verbose_name_plural': 'Yetkazib beruvchilar',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='warehouse.supplier', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name="To'lov miqdori")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('smena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='store.smena', verbose_name='Smena')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='warehouse.supplier', verbose_name='Yetkazib beruvchi')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='accaunt.worker', verbose_name='Hodim')),
            ],
            options={
                'verbose_name': "Yetkazib beruvchi to'lovi",
                'verbose_name_plural': "Yetkazib beruvchi to'lovlari",
                'ordering': ['-created_on'],
            },
        ),
    ]
