# Generated by Django 5.2.11 on 2026-03-23 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_note_to_description'),
        ('warehouse', '0015_rename_note_to_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Aksiya nomi')),
                ('discount_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chegirma (%)')),
                ('valid_from', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('valid_to', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faolmi (qo'lda)")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='warehouse.category', verbose_name='Kategoriyalar')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='warehouse.product', verbose_name='Mahsulotlar')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='store.store', verbose_name="Do'kon")),
                ('subcategories', models.ManyToManyField(blank=True, related_name='promotions', to='warehouse.subcategory', verbose_name='Subkategoriyalar')),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ['-created_on'],
            },
        ),
    ]
