# Generated by Django 5.2.11 on 2026-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_rename_note_to_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='item_discount_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mahsulot chegirma summasi (birlik uchun)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mahsulot chegirmasi (%)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Katalog narxi (chegirmasiz asl narx)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yakuniy jami (miqdor × yakuniy birlik narxi)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yakuniy birlik narxi (barcha chegirmalardan keyin)'),
        ),
    ]
