# Generated by Django 5.2.11 on 2026-03-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_saleitem_discount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Karta to'lov summasi"),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Naqd to'lov summasi"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'langan summa (jami: naqd + karta)"),
        ),
    ]
