# Generated by Django 5.2.11 on 2026-03-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_rename_note_to_description'),
        ('subscription', '0003_rename_note_to_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('category', models.CharField(choices=[('server', 'Server / Hosting'), ('sms', 'SMS xizmat'), ('domain', 'Domain / SSL'), ('marketing', 'Marketing'), ('salary', 'Maosh'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (UZS)')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin xarajati',
                'verbose_name_plural': 'Admin xarajatlari',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kupon kodi')),
                ('type', models.CharField(choices=[('free_days', 'Bepul kunlar'), ('percent_off', 'Foiz chegirma'), ('amount_off', 'Summa chegirma')], max_length=20, verbose_name='Tur')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Qiymat (kun / % / so'm)")),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal foydalanish (null=cheksiz)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan marta')),
                ('valid_from', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('valid_to', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('for_new_only', models.BooleanField(default=False, verbose_name="Faqat yangi do'konlar uchun")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='subscription.subscriptionplan', verbose_name='Faqat ushbu tarif uchun (null=hammaga)')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Berilgan chegirma qiymati')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='superadmin.coupon')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='store.store')),
            ],
            options={
                'verbose_name': 'Kupon foydalanish',
                'verbose_name_plural': 'Kupon foydalanishlar',
                'ordering': ['-applied_at'],
                'unique_together': {('coupon', 'store')},
            },
        ),
    ]
