# Generated by Django 5.2.11 on 2026-03-23 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_note_to_description'),
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='Referral kodi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('rewarded', 'Bonus berildi')], default='pending', max_length=15, verbose_name='Holati')),
                ('reward_days', models.PositiveIntegerField(default=30, verbose_name='Bonus kunlar soni')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('rewarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Bonus berilgan vaqt')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('referred_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_received', to='store.store', verbose_name="Taklif qilingan do'kon")),
                ('referrer_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='store.store', verbose_name="Taklif qilgan do'kon")),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrallar',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StoreReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Referral kodi')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_obj', to='store.store', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': "Do'kon referral kodi",
                'verbose_name_plural': "Do'kon referral kodlari",
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', "Ko'rilmoqda"), ('resolved', 'Hal qilindi'), ('closed', 'Yopildi')], default='open', max_length=15, verbose_name='Holati')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=10, verbose_name='Ustuvorlik')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.store')),
            ],
            options={
                'verbose_name': 'Support ticket',
                'verbose_name_plural': 'Support ticketlar',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Superadmindan')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replies', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='superadmin.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket javob',
                'verbose_name_plural': 'Ticket javoblar',
                'ordering': ['created_on'],
            },
        ),
    ]
