# Generated by Django 5.2.11 on 2026-02-18 06:16

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(help_text='Masalan: product.add, report.view, trade.create', max_length=100, unique=True, verbose_name='Kodi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
            ],
            options={
                'verbose_name': 'Ruxsat',
                'verbose_name_plural': 'Ruxsatlar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone1', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998901234567' formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Asosiy telefon')),
                ('phone2', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998901234567' formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name="Qo'shimcha telefon")),
                ('status', models.BooleanField(default=True, help_text="False bo'lsa, foydalanuvchi tizimga kira olmaydi", verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratdi'), ('update', 'Yangiladi'), ('delete', "O'chirdi"), ('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('assign', 'Tayinladi')], max_length=20, verbose_name='Amal turi')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Model nomi')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Ob'ekt ID")),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Amal bajaruvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(help_text='Masalan: owner, manager, cashier, viewer', max_length=50, unique=True, verbose_name='Kodi')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accaunt.permission', verbose_name='Ruxsatlar')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Maoshi (UZS)')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('deactive', 'Faol emas')], default='active', max_length=10, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='store.branch', verbose_name='Filioli')),
                ('extra_permissions', models.ManyToManyField(blank=True, related_name='workers', to='accaunt.permission', verbose_name="Qo'shimcha ruxsatlar")),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='accaunt.role', verbose_name='Roli')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='store.store', verbose_name="Do'koni")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Hodim',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
    ]
