# Generated by Django 5.2.11 on 2026-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='extra_permissions',
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('owner', 'Egasi'), ('manager', 'Menejer'), ('sotuvchi', 'Sotuvchi')], default='sotuvchi', max_length=20, verbose_name='Roli'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='worker',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Format: {"added": ["sozlamalar"], "removed": ["sklad"]}', verbose_name="Individual permission o'zgarishlar"),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
