# Generated by Django 5.2.11
# Fix: Worker.branch verbose_name 'Filioli' (yozuv xatosi) -> 'Filiali'

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0002_remove_role_permissions_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='workers',
                to='store.branch',
                verbose_name='Filiali',
            ),
        ),
    ]
