# Generated by Django 5.2.11 on 2026-03-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0003_alter_worker_branch_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='extra_permissions',
        ),
        migrations.AddField(
            model_name='worker',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text="Hodim kira oladigan bo'lim kodlari ro'yxati", verbose_name='Ruxsatlar'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('owner', 'Ega'), ('manager', 'Menejer'), ('seller', 'Sotuvchi')], default='seller', max_length=20, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('tatil', 'Tatilda'), ('ishdan_ketgan', 'Ishdan ketgan')], default='active', max_length=15, verbose_name='Holati'),
        ),
    ]
